[package]
name = "bowie-integrate"
version = "0.1.0"
edition = "2026"
rust-version = "1.97"
authors = ["Chenoveko"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Chenoveko/bowie-integrate"
documentation = "https://docs.rs/bowie-integrate"
keywords = ["integration", "numerical", "mathematics", "science"]
categories = ["algorithms", "science"]
include = [
    "/src/**/*.rs",
    "Cargo.toml",
    "README.md"
]
resolver = "2"

[lib]
name = "bowie_integrate"
path = "src/lib.rs"
test = true
bench = false

[dependencies]
